### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by suntao1991** [mitmul/SOINN_CPP#1]
because my research is about soinn,now i need do some experiments,but i have not studied about c++,so ,i cant run this well on my PC,could you help me ?email:365866383@qq.com
thank you!!

**Comment by mitmul** [comment]
@suntao1991 what language is preferable for you?

**Comment by suntao1991** [comment]
i'm good at PHP and JAVA ,and it's harsh for you to  translate this source code to other language,um...,so ,i think i should study deeply on this C++ code you have shared, 
thank you
